// cerver — drive cerver sessions from the terminal.
//
// Subcommands (v1):
//   cerver run [--cli claude|codex|grok] [--on <compute>] [--bill api|sub] "prompt"
//   cerver compare "prompt" <cli> <compute> [<cli> <compute> …]
//   cerver computes [--json]
//
// Reads UA creds from ~/.cerver/infisical.env. Fetches CERVER_API_TOKEN
// (and provider keys when --bill api) at call time. Talks to
// gateway.cerver.ai directly — no local relay required for the CLI
// itself, though the relay is how you get a `cerver_local_provider`
// compute to point at.
package main

import (
	"fmt"
	"os"

	"github.com/eyal-gor/p_71_cerver_cli/cmd"
)

const helpText = `cerver — run AI agents on any compute, from your terminal

usage: cerver <command> [flags] [args]

commands:
  login      Sign in (device-code flow) and write ~/.cerver/cerver.env.
  logout     Revoke the local key server-side and delete cerver.env.
  run        Send a single prompt to one CLI on one compute.
  chat       Multi-turn conversation; resume with: cerver chat <sid>
  compare    Run the same prompt across multiple CLIs in parallel.
  computes   List the computes registered to your account.
  sessions   List recent sessions.
  show       Print a session's full transcript (--follow to stream).
  peek       One-screen snapshot of a session (status + last reply).
  move       Move a live session to a different compute.
  billing    Show this month's cerver bill — service + database fees.
  suggestions Manage the cerver suggestion box:
               list (default) | new "summary"
  help       Show this message.

examples:
  cerver run "what's the time zone of UTC+3?"
  cerver run --cli codex --bill api "summarize today's commits"

  cerver compare "explain Raft leader election" \
    claude mac-mini \
    codex  mac-mini \
    grok   provider_vercel

  cerver compare "fix the failing test" \
    claude mac-mini \
    claude macbook        # A/B the same CLI on two boxes

  cerver computes
  cerver computes --json

config:
  ~/.cerver/infisical.env  Universal Auth creds for your secret vault.
                           Generated by cerver-relay's installer or
                           created by hand. Holds CERVER_API_TOKEN +
                           optional ANTHROPIC_API_KEY / OPENAI_API_KEY /
                           XAI_API_KEY (only needed for --bill api).

billing modes:
  subscription (default for claude / codex): uses your local 'claude login'
                                              or 'codex login' OAuth.
                                              No per-token charge.
  api          (default for grok):           uses the vendor's API key
                                              from your vault. Billed
                                              per token.

  --bill sub     force subscription on this call
  --bill api     force api key on this call
  --bill <cli>=<mode>,<cli>=<mode>  per-CLI override for compare
`

func main() {
	if len(os.Args) < 2 {
		fmt.Print(helpText)
		os.Exit(0)
	}
	cmdName := os.Args[1]
	args := os.Args[2:]

	var err error
	switch cmdName {
	case "login":
		err = cmd.Login(args)
	case "logout":
		err = cmd.Logout(args)
	case "run":
		err = cmd.Run(args)
	case "chat":
		err = cmd.Chat(args)
	case "compare":
		err = cmd.Compare(args)
	case "computes":
		err = cmd.Computes(args)
	case "sessions":
		err = cmd.Sessions(args)
	case "show":
		err = cmd.Show(args)
	case "peek":
		err = cmd.Peek(args)
	case "move":
		err = cmd.Move(args)
	case "billing", "bill":
		err = cmd.Billing(args)
	case "suggestions", "suggest":
		err = cmd.Suggestions(args)
	case "help", "-h", "--help":
		fmt.Print(helpText)
		return
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", cmdName)
		fmt.Print(helpText)
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
